// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://bhtxgnqtnfvuehddkasg.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_FV9GdWPBR-SIzJk8bNGenQ_aFBLEccq';

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

export const isSupabaseConfigured = true;
